import type { Product, Review } from "@/lib/types";

export const demoProducts: Product[] = [
  {
    id: "NM-BAG-1001",
    name: "Aster Carry Pack",
    slug: "aster-carry-pack",
    description: "A compact everyday backpack with structured pockets and weather-resistant fabric.",
    price: 18990,
    stock: 42,
    category: "Bags",
    seller_name: "Orion Goods",
    image_url: "/products/aster-pack.svg",
    average_rating: 4.6,
  },
  {
    id: "NM-HOME-1002",
    name: "LumaDesk Lamp",
    slug: "lumadesk-lamp",
    description: "A dimmable desk lamp with warm focus modes for study and remote work.",
    price: 11990,
    stock: 28,
    category: "Home Office",
    seller_name: "Kairo Studio",
    image_url: "/products/lumadesk-lamp.svg",
    average_rating: 4.4,
  },
  {
    id: "NM-KIT-1003",
    name: "Mira Ceramic Mug",
    slug: "mira-ceramic-mug",
    description: "A satin-finish ceramic mug with a comfortable handle and steady heat retention.",
    price: 2950,
    stock: 58,
    category: "Kitchen",
    seller_name: "Juniper Tableware",
    image_url: "/products/mira-mug.svg",
    average_rating: 4.8,
  },
  {
    id: "NM-AUD-1004",
    name: "VoltEdge Earbuds",
    slug: "voltedge-earbuds",
    description: "Wireless earbuds with clear call pickup and long commute battery life.",
    price: 21990,
    stock: 35,
    category: "Electronics",
    seller_name: "Northline Audio",
    image_url: "/products/voltedge-earbuds.svg",
    average_rating: 4.1,
  },
  {
    id: "NM-FIT-1005",
    name: "Forma Training Bottle",
    slug: "forma-training-bottle",
    description: "A leak-resistant training bottle with a soft-touch grip and measured side markers.",
    price: 4990,
    stock: 64,
    category: "Fitness",
    seller_name: "Pulse Yard",
    image_url: "/products/forma-bottle.svg",
    average_rating: 4.5,
  },
  {
    id: "NM-HOME-1006",
    name: "Halo Desk Fan",
    slug: "halo-desk-fan",
    description: "A compact desk fan with quiet airflow settings and a stable weighted base.",
    price: 8990,
    stock: 26,
    category: "Home Office",
    seller_name: "Kairo Studio",
    image_url: "/products/halo-desk-fan.svg",
    average_rating: 4.3,
  },
  {
    id: "NM-ELEC-1007",
    name: "Nova Charge Dock",
    slug: "nova-charge-dock",
    description: "A vertical charging dock for phones and earbuds with a tidy cable channel.",
    price: 14500,
    stock: 31,
    category: "Electronics",
    seller_name: "Northline Audio",
    image_url: "/products/nova-charge-dock.svg",
    average_rating: 4.6,
  },
  {
    id: "NM-KITCH-1008",
    name: "Cinder Brew Kettle",
    slug: "cinder-brew-kettle",
    description: "A stovetop-style electric kettle with a precision spout for pour-over brewing.",
    price: 16990,
    stock: 17,
    category: "Kitchen",
    seller_name: "Juniper Tableware",
    image_url: "/products/cinder-brew-kettle.svg",
    average_rating: 4.7,
  },
  {
    id: "NM-BAG-1009",
    name: "Cove Sling Bag",
    slug: "cove-sling-bag",
    description: "A slim crossbody sling with hidden zip pockets and easy everyday organization.",
    price: 10990,
    stock: 40,
    category: "Bags",
    seller_name: "Orion Goods",
    image_url: "/products/cove-sling-bag.svg",
    average_rating: 4.4,
  },
  {
    id: "NM-FIT-1010",
    name: "Pulse Yoga Mat",
    slug: "pulse-yoga-mat",
    description: "A thick exercise mat with textured grip and a travel carry strap.",
    price: 7990,
    stock: 33,
    category: "Fitness",
    seller_name: "Pulse Yard",
    image_url: "/products/pulse-yoga-mat.svg",
    average_rating: 4.5,
  },
  {
    id: "NM-HOME-1011",
    name: "Pixel Note Stand",
    slug: "pixel-note-stand",
    description: "A fold-flat tablet and notebook stand for cleaner video calls and study sessions.",
    price: 5990,
    stock: 52,
    category: "Home Office",
    seller_name: "Kairo Studio",
    image_url: "/products/pixel-note-stand.svg",
    average_rating: 4.2,
  },
  {
    id: "NM-HOME-1012",
    name: "Nori Storage Box",
    slug: "nori-storage-box",
    description: "A stackable organizer box with a fabric pull tab and soft-lid closure.",
    price: 4750,
    stock: 70,
    category: "Home",
    seller_name: "Harbor Nest",
    image_url: "/products/nori-storage-box.svg",
    average_rating: 4.1,
  },
  {
    id: "NM-ELEC-1013",
    name: "Arc Mouse Pad",
    slug: "arc-mouse-pad",
    description: "A large desk mat with clean stitched edges and a smooth glide surface.",
    price: 4250,
    stock: 62,
    category: "Electronics",
    seller_name: "Northline Audio",
    image_url: "/products/arc-mouse-pad.svg",
    average_rating: 4.3,
  },
  {
    id: "NM-KITCH-1014",
    name: "Ridge Lunch Box",
    slug: "ridge-lunch-box",
    description: "A lock-seal lunch box with two inner compartments and a matte finish shell.",
    price: 5450,
    stock: 44,
    category: "Kitchen",
    seller_name: "Juniper Tableware",
    image_url: "/products/ridge-lunch-box.svg",
    average_rating: 4.4,
  },
  {
    id: "NM-HOME-1015",
    name: "Solace Table Lamp",
    slug: "solace-table-lamp",
    description: "A warm ambient table lamp with a soft linen shade and low-glare evening light.",
    price: 13490,
    stock: 24,
    category: "Home",
    seller_name: "Harbor Nest",
    image_url: "/products/solace-table-lamp.svg",
    average_rating: 4.7,
  },
  {
    id: "NM-ACC-1016",
    name: "Quill Pen Cup",
    slug: "quill-pen-cup",
    description: "A ceramic desktop pen cup with a weighted base and matte exterior glaze.",
    price: 3250,
    stock: 55,
    category: "Accessories",
    seller_name: "Harbor Nest",
    image_url: "/products/quill-pen-cup.svg",
    average_rating: 4.0,
  },
  {
    id: "NM-ACC-1017",
    name: "Atlas Travel Thermos",
    slug: "atlas-travel-thermos",
    description: "A stainless travel thermos that keeps drinks hot for long commutes and early starts.",
    price: 6890,
    stock: 47,
    category: "Accessories",
    seller_name: "Pulse Yard",
    image_url: "/products/atlas-travel-thermos.svg",
    average_rating: 4.6,
  },
  {
    id: "NM-ELEC-1018",
    name: "Drift Sound Speaker",
    slug: "drift-sound-speaker",
    description: "A compact Bluetooth speaker with balanced sound and a textured carry loop.",
    price: 15490,
    stock: 29,
    category: "Electronics",
    seller_name: "Northline Audio",
    image_url: "/products/drift-sound-speaker.svg",
    average_rating: 4.5,
  },
  {
    id: "NM-HOME-1019",
    name: "Lattice Wall Shelf",
    slug: "lattice-wall-shelf",
    description: "A minimal wall shelf for small decor pieces, cables, or bedside essentials.",
    price: 9490,
    stock: 21,
    category: "Home",
    seller_name: "Harbor Nest",
    image_url: "/products/lattice-wall-shelf.svg",
    average_rating: 4.2,
  },
  {
    id: "NM-FIT-1020",
    name: "Stride Recovery Roller",
    slug: "stride-recovery-roller",
    description: "A medium-density recovery roller for post-workout mobility and everyday stretching.",
    price: 6150,
    stock: 36,
    category: "Fitness",
    seller_name: "Pulse Yard",
    image_url: "/products/stride-recovery-roller.svg",
    average_rating: 4.4,
  },
];

export const demoFlaggedReviews: Review[] = [
  {
    id: "RVW-7003",
    product_id: "NM-HOME-1002",
    user_id: "USR-84729",
    rating: 5,
    title: "Best product",
    body: "good product",
    status: "flagged",
    risk_score: 48,
    risk_label: "Suspicious",
    is_verified_purchase: false,
    created_at: new Date().toISOString(),
    profiles: { full_name: "", username: "user84729" },
    products: { name: "LumaDesk Lamp" },
    review_flags: [
      { category: "Text Risk", rule_code: "GENERIC_REVIEW", reason: "Review uses generic wording.", score_impact: 9 },
      { category: "Profile Risk", rule_code: "NO_VERIFIED_PURCHASE", reason: "User has no purchase history for this product.", score_impact: 8 },
    ],
  },
  {
    id: "RVW-7004",
    product_id: "NM-HOME-1002",
    user_id: "USR-91384",
    rating: 5,
    title: "Amazing",
    body: "Amazing amazing amazing must buy best ever guaranteed perfect item!!!",
    status: "quarantined",
    risk_score: 72,
    risk_label: "High Risk",
    is_verified_purchase: false,
    created_at: new Date().toISOString(),
    profiles: { full_name: "", username: "user91384" },
    products: { name: "LumaDesk Lamp" },
    review_flags: [
      { category: "Text Risk", rule_code: "REPEATED_WORDS", reason: "Review repeats words unnaturally.", score_impact: 8 },
      { category: "Text Risk", rule_code: "MARKETING_LANGUAGE", reason: "Review uses promotional language.", score_impact: 8 },
      { category: "Profile Risk", rule_code: "NEW_ACCOUNT", reason: "User account is newly created.", score_impact: 8 },
    ],
  },
];
